#pragma once

#include "CoreMinimal.h"


DECLARE_STATS_GROUP(TEXT("XSPLoader"), STATGROUP_XSPLoader, STATCAT_Advanced);

DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num Node"), STAT_XSPLoader_NumNode, STATGROUP_XSPLoader);
DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num LevelOneNode"), STAT_XSPLoader_NumLevelOneNode, STATGROUP_XSPLoader);
DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num LeafNode"), STAT_XSPLoader_NumLeafNode, STATGROUP_XSPLoader);

DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num BatchComponent"), STAT_XSPLoader_NumBatchComponent, STATGROUP_XSPLoader);

DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num TotalVertices"), STAT_XSPLoader_NumTotalVertices, STATGROUP_XSPLoader);
DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num RegisteredVertices"), STAT_XSPLoader_NumRegisteredVertices, STATGROUP_XSPLoader);
DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num RegisteredComponents"), STAT_XSPLoader_NumRegisteredComponents, STATGROUP_XSPLoader);
DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num CreatedPhysicsState"), STAT_XSPLoader_NumCreatedPhysicsState, STATGROUP_XSPLoader);

DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("MaxNumVerticesPerBatch"), STAT_XSPLoader_MaxNumVerticesPerBatch, STATGROUP_XSPLoader);
DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("MinNumVerticesPerBatch"), STAT_XSPLoader_MinNumVerticesPerBatch, STATGROUP_XSPLoader);
DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("MinNumVerticesUnbatch"), STAT_XSPLoader_MinNumVerticesUnbatch, STATGROUP_XSPLoader);

DECLARE_FLOAT_ACCUMULATOR_STAT(TEXT("ReadFileTime"), STAT_XSPLoader_ReadFileTime, STATGROUP_XSPLoader);

DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num RawMesh"), STAT_XSPLoader_NumRawMesh, STATGROUP_XSPLoader);
DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num CylinderMesh"), STAT_XSPLoader_NumCylinderMesh, STATGROUP_XSPLoader);
DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num EllipticalMesh"), STAT_XSPLoader_NumEllipticalMesh, STATGROUP_XSPLoader);

DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num RawMeshSimplified"), STAT_XSPLoader_NumRawMeshSimplified, STATGROUP_XSPLoader);
DECLARE_DWORD_ACCUMULATOR_STAT(TEXT("Num TotalVerticesSimplied"), STAT_XSPLoader_NumTotalVerticesSimplied, STATGROUP_XSPLoader);
